"""
migrate_sqlite_to_postgres.py — one-time SQLite -> Supabase Postgres copy (Phase 1)
===================================================================================
Recreate the SQLite schema in Postgres and copy every row, with ZERO intended
behavior change. This is the Phase-1 "data parity" migration: after it runs,
`walkforward.py` pointed at Postgres must reproduce the pre-migration WA MAE
(0.631 honest) exactly. Still single-user at this stage — no `user_id` yet.

Type mapping (the parity trap the brief warns about — REAL vs NUMERIC):
    SQLite REAL     -> Postgres DOUBLE PRECISION   (float8; matches SQLite's 8-byte
                       REAL and Python float. NOT `REAL`/float4 = lossy, NOT
                       `NUMERIC` = returns Decimal and changes downstream math.)
    SQLite INTEGER  -> Postgres BIGINT
    SQLite TEXT     -> Postgres TEXT
    (unknown/blank affinity -> TEXT; BLOB -> BYTEA)

Primary keys:
    `id INTEGER PRIMARY KEY`        -> BIGINT GENERATED BY DEFAULT AS IDENTITY
                                       (SQLite's rowid-alias autoincrement; existing
                                       ids are copied verbatim, then the identity
                                       sequence is advanced past MAX(id)).
    `position INTEGER PRIMARY KEY`  -> BIGINT PRIMARY KEY (app-managed, not auto).
    `<col> TEXT PRIMARY KEY`        -> preserved as-is.
    tables with no PK               -> no PK (e.g. gcomp_weights).

Usage:
    DATABASE_URL=postgres://...  python3 migrate_sqlite_to_postgres.py        # migrate
    python3 migrate_sqlite_to_postgres.py --check      # PREVIEW the DDL + source
                                                       # row counts; no Postgres
                                                       # connection, no writes.
    DATABASE_URL=...  python3 migrate_sqlite_to_postgres.py --drop            # drop+recreate
    DATABASE_URL=...  python3 migrate_sqlite_to_postgres.py --verify-only     # counts only

DATABASE_URL is read from the environment (never hardcoded). psycopg2 is imported
lazily, so `--check` runs with only the standard library.
"""

import argparse
import os
import sqlite3
import sys

DEFAULT_SQLITE = "books.db"

# SQLite declared-type (uppercased) -> Postgres type. See the module docstring for
# why REAL maps to DOUBLE PRECISION and not NUMERIC.
TYPE_MAP = {
    "INTEGER": "BIGINT",
    "INT": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "FLOAT": "DOUBLE PRECISION",
    "DOUBLE": "DOUBLE PRECISION",
    "TEXT": "TEXT",
    "CLOB": "TEXT",
    "VARCHAR": "TEXT",
    "": "TEXT",
    "BLOB": "BYTEA",
    "NUMERIC": "DOUBLE PRECISION",
    "BOOLEAN": "BOOLEAN",
}


def pg_type(sqlite_decl_type):
    key = (sqlite_decl_type or "").strip().upper()
    # strip any size/precision, e.g. VARCHAR(50) -> VARCHAR
    key = key.split("(")[0].strip()
    return TYPE_MAP.get(key, "TEXT")


def q(ident):
    """Double-quote a Postgres identifier, preserving case (component columns like
    "Emotional Impact" must stay quoted everywhere)."""
    return '"' + ident.replace('"', '""') + '"'


def sqlite_tables(scon):
    rows = scon.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


def sqlite_columns(scon, table):
    """Return PRAGMA table_info rows as dicts: name, type, notnull, dflt, pk."""
    cols = []
    for cid, name, ctype, notnull, dflt, pk in scon.execute(
        f"PRAGMA table_info({q_sqlite(table)})"
    ).fetchall():
        cols.append(
            {"name": name, "type": ctype, "notnull": bool(notnull),
             "dflt": dflt, "pk": int(pk)}
        )
    return cols


def q_sqlite(ident):
    return '"' + ident.replace('"', '""') + '"'


def build_ddl(table, cols):
    """Generate the Postgres CREATE TABLE for one SQLite table."""
    lines = []
    pk_cols = [c for c in cols if c["pk"]]
    single_pk = pk_cols[0]["name"] if len(pk_cols) == 1 else None

    for c in cols:
        name, decl = c["name"], pg_type(c["type"])
        is_identity = (
            single_pk == name
            and name.lower() == "id"
            and pg_type(c["type"]) == "BIGINT"
        )
        piece = f"    {q(name)} "
        if is_identity:
            piece += "BIGINT GENERATED BY DEFAULT AS IDENTITY"
        else:
            piece += decl
        if single_pk == name:
            piece += " PRIMARY KEY"
        if c["notnull"] and single_pk != name:
            piece += " NOT NULL"
        if c["dflt"] is not None:
            # PRAGMA gives the default as raw SQL text (e.g. 'finished', 0, 1);
            # these literal forms are identical in SQLite and Postgres.
            piece += f" DEFAULT {c['dflt']}"
        lines.append(piece)

    # Composite / no-name-matched PKs (none in the current schema, but be safe).
    if len(pk_cols) > 1:
        lines.append("    PRIMARY KEY (" + ", ".join(q(c["name"]) for c in pk_cols) + ")")

    return f"CREATE TABLE {q(table)} (\n" + ",\n".join(lines) + "\n);"


def copy_table(scon, pcon, table, cols):
    """Copy every row of one table SQLite -> Postgres, preserving values/ids."""
    import psycopg2.extras as extras

    col_names = [c["name"] for c in cols]
    src_rows = scon.execute(
        f"SELECT {', '.join(q_sqlite(cn) for cn in col_names)} FROM {q_sqlite(table)}"
    ).fetchall()
    if not src_rows:
        return 0
    collist = ", ".join(q(cn) for cn in col_names)
    with pcon.cursor() as cur:
        extras.execute_values(
            cur,
            f"INSERT INTO {q(table)} ({collist}) VALUES %s",
            src_rows,
            page_size=500,
        )
    return len(src_rows)


def reset_identity(pcon, table, cols):
    """Advance the IDENTITY sequence for an `id` column past the copied MAX(id)."""
    has_id_identity = any(
        c["pk"] and c["name"].lower() == "id" and pg_type(c["type"]) == "BIGINT"
        for c in cols
    )
    if not has_id_identity:
        return
    with pcon.cursor() as cur:
        cur.execute(
            f"SELECT setval("
            f"  pg_get_serial_sequence(%s, 'id'), "
            f"  COALESCE((SELECT MAX(id) FROM {q(table)}), 1), "
            f"  (SELECT COUNT(*) FROM {q(table)}) > 0"
            f")",
            (table,),
        )


def do_check(scon, tables):
    """Preview mode: print the planned DDL and source row counts. No Postgres."""
    print("=" * 70)
    print("PREVIEW (--check): planned Postgres schema + source row counts")
    print("No Postgres connection opened, no rows written.")
    print("=" * 70)
    total = 0
    for t in tables:
        cols = sqlite_columns(scon, t)
        n = scon.execute(f"SELECT COUNT(*) FROM {q_sqlite(t)}").fetchone()[0]
        total += n
        print(f"\n-- {t}  ({n} rows) " + "-" * (48 - len(t)))
        print(build_ddl(t, cols))
    print(f"\n{len(tables)} tables, {total} total rows planned for copy.")


def do_verify(scon, pcon, tables):
    """Compare row counts table-by-table."""
    print("\nRow-count verification (SQLite vs Postgres):")
    all_ok = True
    for t in tables:
        s = scon.execute(f"SELECT COUNT(*) FROM {q_sqlite(t)}").fetchone()[0]
        with pcon.cursor() as cur:
            cur.execute(f"SELECT COUNT(*) FROM {q(t)}")
            p = cur.fetchone()[0]
        ok = s == p
        all_ok = all_ok and ok
        print(f"  [{'OK ' if ok else 'MISMATCH'}] {t:<28} sqlite={s:<6} postgres={p}")
    return all_ok


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sqlite", default=DEFAULT_SQLITE, help="source SQLite path")
    ap.add_argument("--check", action="store_true",
                    help="preview DDL + counts only; no Postgres, no writes")
    ap.add_argument("--drop", action="store_true",
                    help="DROP TABLE IF EXISTS before creating (destructive on target)")
    ap.add_argument("--verify-only", action="store_true",
                    help="only compare row counts; no schema/data writes")
    args = ap.parse_args()

    if not os.path.exists(args.sqlite):
        sys.exit(f"ERROR: SQLite source not found: {args.sqlite}")

    scon = sqlite3.connect(args.sqlite)
    tables = sqlite_tables(scon)

    if args.check:
        do_check(scon, tables)
        return

    # Everything below needs a live Postgres.
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        sys.exit(
            "ERROR: DATABASE_URL is not set. Provide the Supabase Postgres "
            "connection string via the DATABASE_URL env var (never hardcoded). "
            "Use --check to preview the migration without a database."
        )
    try:
        import psycopg2
    except ImportError:
        sys.exit("ERROR: psycopg2 not installed. Run: pip install psycopg2-binary")

    pcon = psycopg2.connect(url)
    try:
        if args.verify_only:
            ok = do_verify(scon, pcon, tables)
            sys.exit(0 if ok else 1)

        for t in tables:
            cols = sqlite_columns(scon, t)
            with pcon.cursor() as cur:
                if args.drop:
                    cur.execute(f"DROP TABLE IF EXISTS {q(t)} CASCADE")
                cur.execute(build_ddl(t, cols))
            pcon.commit()
            n = copy_table(scon, pcon, t, cols)
            reset_identity(pcon, t, cols)
            pcon.commit()
            print(f"  migrated {t:<28} {n} rows")

        ok = do_verify(scon, pcon, tables)
        print("\n" + ("PARITY: all row counts match." if ok
                      else "PARITY FAILED: row-count mismatch — investigate."))
        sys.exit(0 if ok else 1)
    finally:
        pcon.close()
        scon.close()


if __name__ == "__main__":
    main()
